### ISSUE TITLE
Question about "Avoid method calls or property accesses on a "dynamic" target"

### ISSUE THREAD

**Issue by portlek** [forus-labs/cauldron#2]
I couldn't find a fix for this lint. I look up to the documentation page but i couldn't understand how to fix this code.
![image](https://user-images.githubusercontent.com/12835420/153631826-6eb6bdca-f2ec-4a88-8ee9-e64358a6fbe6.png)
```dart
jsonDecode(value.data)
  .cast<Map<String, dynamic>>()
  .map<Categories>(Categories.fromJson)
  .toList()
```

**Comment by Pante** [comment]
`jsonDecode(value.data)` returns `dynamic`. Since the receiver is `dynamic`, subsequently calling `.cast<Map<String, dynamic>>()` causes the warning. To fix the issue, you probably need to rewrite it as `(jsonDecode(value.data) as Map<String, dynamic>).map<Categories>(Categories.fromJson).toList()`.

On another note, I think you're misusing `.map(...)`. Calling `.map(...)` on a map requires two type parameters but you only provided one, see https://api.dart.dev/stable/2.16.1/dart-core/Map/map.html. Perhaps you meant to map the keys/values?
